# Generated by Django 3.2.25 on 2024-10-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('description', models.TextField(default='Description')),
                ('address', models.CharField(default='Address', max_length=254)),
                ('phone', models.CharField(default='Phone', max_length=20)),
                ('NumberOfOrders', models.IntegerField(default=0)),
                ('orders', models.CharField(default='Not ANY ORDRS', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
